name: Binary gems

on: [push, pull_request]

jobs:
  job_build_binary_gems:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "x86_64-linux"
          - platform: "x86_64-darwin"
          - platform: "arm64-darwin"
          - platform: "aarch64-linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Create a dummy cert to satisfy the build
        run: |
          mkdir -p ~/.gem/
          ruby -ropenssl -e "puts OpenSSL::PKey::RSA.new(2048).to_pem" > ~/.gem/gem-private_key.pem
          gem cert --build ci@dummy.org --private-key ~/.gem/gem-private_key.pem
          cp gem-public_cert.pem ~/.gem/gem-public_cert.pem

      - name: Build binary gem
        run: bundle exec rake gem:cross:${{ matrix.platform }}

      - name: Upload binary gem
        uses: actions/upload-artifact@v2
        with:
          name: binary-gem
          path: pkg/*.gem
